# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'ZZKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZKit
  #pod 'CTMediator'
  pod 'YYKit'

  # private pods
  #pod 'ZZKitSetting'


  # local pods
  pod 'ZZDiscover_Category', :path => '../ZZDiscover_Category'
  pod 'ZZDiscover', :path => '../ZZDiscover'

# https://blog.codemagic.io/code-signing-issues-in-xcode-14-and-how-to-fix-them/
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
#            config.build_settings["DEVELOPMENT_TEAM"] = "687C4JR3J3"
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end

end
